### ISSUE TITLE
Items overlap in footer

### ISSUE THREAD

**Issue by kiaukko** [serveri/new.serveriry.fi.nuxtjs#5]
### Kuvaile bugia

When you scale the browser window, the "© 2023 Serveri ry" overlaps the instagram- and telegram-icons.
![footerbug](https://github.com/serveri/new.serveriry.fi.nuxtjs/assets/102158536/909b2c92-71a8-46da-8e62-aa4f150a66a7)

### Odotettu käyttäytyminen

The text should not overlap the icons :D It should either be, at least little bit to the left or in the left corner overall, or the text and icons should be in a column

### Miten bugi toistetaan?

Open the webpage on computer, scroll down and start scaling the window to make it narrower.

### Turvallisen tilan periaatteet

- [X] Sitoudun noudattamaan turvallisemman tilan periaatteita

**Comment by Jeb4dev** [comment]
fixed in https://codeberg.org/serveriry/new.serveriry.fi.nuxtjs/pulls/41

once again thanks for bug report 😃
